# Select your base image
FROM ubuntu:latest

# Set the working directory in the image(/app can be any name e.g /home, /my project)
WORKDIR /app

# Copy the files from the host file system to the image file system
COPY . /app

# Update Ubuntu package list 
# Install the necessary packages required to run application
RUN apt-get update && apt-get install -y python3 python3-pip

# Set environment variables
ENV NAME Shahana

# Run a command to start the application
CMD ["python3", "app.py"]
